CREATE TABLE IF NOT EXISTS USERS(
    email VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT PK_USER_EMAIL PRIMARY KEY(email),
    CONSTRAINT UNIQUE_USER_NAME UNIQUE(name)
);